### PR TITLE
Center Save Notification

### PR DESCRIPTION
**Pull request by AnthonyEstrada**
Current Saved Notification Position. 
image

### CODE REVIEW

**Comment by AnthonyEstrada** [comment]
@blainekasten  It seems to me when I do change the browser size or use the mobile emulator the "Saved" notification is centered. I haven't found a way that works better than this. I could use some help and or direction here. Thanks

**Comment by AnthonyEstrada** [comment]
@blainekasten I've added what I think you were looking for.

**Comment by blainekasten** [comment]
@AnthonyEstrada you are super close. Did you test it and see how it looked right now? You can notice it best if you make your browser small (mobile like) to test it. 

That translateX is definitely what was missing, but translateX moves along the x axis from the left. So I think coming from 50% right is messing it up a little bit. It's super close though!

**Comment by blainekasten** [comment]
@AnthonyEstrada awesome work! Thanks so much!

**Pull request merged**
